# 章立てをする
\#の数だけ階層を変えられる。

> \# 章
> \#\# 節
> \#\#\# 項
> \#\#\#\# 次

## 節
### 項
#### 次


# Bookdownの再現 
## 練習ファイルのダウンロード
GitHubにある[修士のススメ](https://github.com/tabutan/GetStartedMaster.git)にある「練習用ファイル一覧」フォルダーをダウンロード。

Knitしてみると、本サイトの「0 はじめに」と同じものが表示されるはずである。
ここで表示されている内容は[ヤクシマザルという生き物を知りたい](https://tabutan.github.io/yakuzaru/)にあるものと同じものです。

## Build Bookしてみよう
一応KnitでもHTMLが出現したと思うが、GitBookの場合はエラーの元（例えば、ある章を閲覧できないなど）。Q & AにあるGitBookの立ち上げ方を読み、Build Bookしてみよう。


# 文章を書く練習

## 太字、イタリック
文章はそのまま書けばOK。

太字は、太字にしたい部分を\_\_または\*\*で囲めばOK。

> \*\*ぽよよん\*\*

>\_\_ぽよよん\_\_

**ぽよよん** <br>
__ぽよよん__

イタリックは\_または\*で囲む。

> \*italic\*、\_italic\_、\*字体によってイタリックに見えないものあり！\*

*italic*、_italic_、*字体によってイタリックに見えないものあり！*

## 箇条書き
半角でマイナス記号、半角スペース　<br>
箇条書きの中の箇条書き：tabキー押して、半角でマイナス記号、半角スペース

- 箇条書き
  - 修士向け
  - 知らなくても大丈夫
  - のんびりできないし
  - すんなりいかない
  - スケジュール
  - 目指せ修士号取得
  
## 数式
文章中の数式は\$で囲む。

> 個体追跡法でアカンボウを行動観察した（\$N=12\$、\$n=225\$）。

個体追跡法でアカンボウを行動観察した（$N=12$、$n=225$）。

### 下付き文字、上付き文字
\$で囲んで、下付きにしたい文字をアンダーバーと{}で括る。1文字なら{}は省略可。上付き文字はアンダーバーの代わりに^を使う。

> \$N_a\$、\$N^a\$、\$N_{修士のススメ参加者}=7\$

$N_a$、$N^a$、$N_{修士のススメ参加者}=7$

## コメントアウト
隠したい文章は、「\<!-- 〇〇 \-->」でコメントアウトできる 

> \<!-- 見られたくない、見られたくない \-->、無事消えたかな？

<!-- 見られたくない、見られたくない -->、無事消えたかな？

## 引用文献
>ヤクシマザルは他地域のニホンザルより体毛が黒い [\@hamada1992]

ヤクシマザルは他地域のニホンザルより体毛が黒い [@hamada1992]

> ニホンザルの研究はいろいろある [\@hamada1992; \@hikida2022]

ニホンザルの研究はいろいろある [@hamada1992; @hikida2022]

おっと、Hikida 2022の引用文献に問題発生。
Japanese macaquesにすべきところをjapanese macaquesと表示されているし、種名がイタリックになっていない！

**対処法**

bibファイルの中でHikida 2022に該当する箇所を探す。

>\@article{hikida2022,<br>
author = {Hikida, K.},<br>
title = {Eyeblink rate as an indicator of concentration on grooming in Japanese macaques (Macaca fuscata)},<br>
journal = {American Journal of Primatology},<br>
volume = {84},<br>
number = {7},<br>
pages = {e23392},

title = {xxxxxxx}担っているところをtitle ={{xxxxx}}に変更してみよう。小文字が大文字に変更されているはず。

次に、イタリック。

イタリックにしたい箇所を\\textit{xxxxx}で囲ってみよう。種名がイタリックになっているはず。
